### ISSUE TITLE
Account for 'date' inputs

### ISSUE THREAD

**Issue by ghost** [DFMCH/dfm_web#24]
DFM Web doesn't apply its `input` rules to `type="date"`.

Also dates need extra `padding-left` and a `min-height`. The rules I have in tracker are:

```
input[type="date"]{
  padding-left: 5px;
  min-height: 2.3em;
}
```
## DFM Web (example):

![screenshot from 2016-07-21 11 19 35](https://cloud.githubusercontent.com/assets/13771755/17030489/3b78100c-4f35-11e6-8f0e-c31a1c9d440f.png)
## Tracker (example):

![screenshot from 2016-07-21 11 20 35](https://cloud.githubusercontent.com/assets/13771755/17030506/48fe77c0-4f35-11e6-9078-2c6362961233.png)

**Comment by duffyjp** [comment]
This issue has been silent for 3 years, closing.
