### ISSUE TITLE
Another weird edge case for navbar

### ISSUE THREAD

**Issue by justinsamsky** [DFMCH/dfm_web#25]
Small shows the 'burger:
![screenshot from 2016-07-28 14 24 04](https://cloud.githubusercontent.com/assets/13771755/17226493/6349740a-54cf-11e6-967a-534103120471.png)

The lower range of Medium sizes shows no menu:
![screenshot from 2016-07-28 14 24 14](https://cloud.githubusercontent.com/assets/13771755/17226491/60136bb0-54cf-11e6-8d23-6c99d05e96bc.png)

A few pixels wider, and the menu links show:
![screenshot from 2016-07-28 14 24 36](https://cloud.githubusercontent.com/assets/13771755/17226490/5dadcffa-54cf-11e6-913c-c54e63dcb448.png)

**Comment by duffyjp** [comment]
Fixed
