### ISSUE TITLE
Titlebar font - maybe smaller for mobile?

### ISSUE THREAD

**Issue by ghost** [DFMCH/dfm_web#29]
Portrait view on an iPhone 5:

![img_1703](https://cloud.githubusercontent.com/assets/13771755/17605695/54b692c0-5fe1-11e6-89af-6cfe86ce9610.jpg)

**Comment by duffyjp** [comment]
Looks fine to me.

<img width="367" alt="Screen Shot 2019-10-22 at 10 29 45 AM" src="https://user-images.githubusercontent.com/382216/67302709-e97cb480-f4b6-11e9-8791-7eda21c3c4e7.png">
